repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: debug-statements
  - id: check-ast
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # needed for !! tags in mkdocs.yml
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.11.9'  # make sure this is always consistent with hatch configs
  hooks:
    - id: ruff
    - id: ruff-format
      args: [--check, --config, ./pyproject.toml]
