name: build moose
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build wheel and source artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install build frontend
        run: uv pip install hatch
      - name: Build
        run: hatch build
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: dist/*
          if-no-files-found: error


  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/moose-spectra
    permissions:
      id-token: write
    steps:
      - name: Download python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1